// Province italiane (sigle ufficiali). EE e' il codice usato
// dall'amministrazione per chi e' nato in uno stato estero: lo stesso che
// compare nel codice fiscale al posto del codice catastale del comune.
export const PROVINCE_ITALIANE: { value: string; label: string }[] = [
  { value: "AG", label: "AG - Agrigento" },
  { value: "AL", label: "AL - Alessandria" },
  { value: "AN", label: "AN - Ancona" },
  { value: "AO", label: "AO - Aosta" },
  { value: "AP", label: "AP - Ascoli Piceno" },
  { value: "AQ", label: "AQ - L'Aquila" },
  { value: "AR", label: "AR - Arezzo" },
  { value: "AT", label: "AT - Asti" },
  { value: "AV", label: "AV - Avellino" },
  { value: "BA", label: "BA - Bari" },
  { value: "BG", label: "BG - Bergamo" },
  { value: "BI", label: "BI - Biella" },
  { value: "BL", label: "BL - Belluno" },
  { value: "BN", label: "BN - Benevento" },
  { value: "BO", label: "BO - Bologna" },
  { value: "BR", label: "BR - Brindisi" },
  { value: "BS", label: "BS - Brescia" },
  { value: "BT", label: "BT - Barletta-Andria-Trani" },
  { value: "BZ", label: "BZ - Bolzano" },
  { value: "CA", label: "CA - Cagliari" },
  { value: "CB", label: "CB - Campobasso" },
  { value: "CE", label: "CE - Caserta" },
  { value: "CH", label: "CH - Chieti" },
  { value: "CL", label: "CL - Caltanissetta" },
  { value: "CN", label: "CN - Cuneo" },
  { value: "CO", label: "CO - Como" },
  { value: "CR", label: "CR - Cremona" },
  { value: "CS", label: "CS - Cosenza" },
  { value: "CT", label: "CT - Catania" },
  { value: "CZ", label: "CZ - Catanzaro" },
  { value: "EN", label: "EN - Enna" },
  { value: "FC", label: "FC - Forlì-Cesena" },
  { value: "FE", label: "FE - Ferrara" },
  { value: "FG", label: "FG - Foggia" },
  { value: "FI", label: "FI - Firenze" },
  { value: "FM", label: "FM - Fermo" },
  { value: "FR", label: "FR - Frosinone" },
  { value: "GE", label: "GE - Genova" },
  { value: "GO", label: "GO - Gorizia" },
  { value: "GR", label: "GR - Grosseto" },
  { value: "IM", label: "IM - Imperia" },
  { value: "IS", label: "IS - Isernia" },
  { value: "KR", label: "KR - Crotone" },
  { value: "LC", label: "LC - Lecco" },
  { value: "LE", label: "LE - Lecce" },
  { value: "LI", label: "LI - Livorno" },
  { value: "LO", label: "LO - Lodi" },
  { value: "LT", label: "LT - Latina" },
  { value: "LU", label: "LU - Lucca" },
  { value: "MB", label: "MB - Monza e della Brianza" },
  { value: "MC", label: "MC - Macerata" },
  { value: "ME", label: "ME - Messina" },
  { value: "MI", label: "MI - Milano" },
  { value: "MN", label: "MN - Mantova" },
  { value: "MO", label: "MO - Modena" },
  { value: "MS", label: "MS - Massa-Carrara" },
  { value: "MT", label: "MT - Matera" },
  { value: "NA", label: "NA - Napoli" },
  { value: "NO", label: "NO - Novara" },
  { value: "NU", label: "NU - Nuoro" },
  { value: "OR", label: "OR - Oristano" },
  { value: "PA", label: "PA - Palermo" },
  { value: "PC", label: "PC - Piacenza" },
  { value: "PD", label: "PD - Padova" },
  { value: "PE", label: "PE - Pescara" },
  { value: "PG", label: "PG - Perugia" },
  { value: "PI", label: "PI - Pisa" },
  { value: "PN", label: "PN - Pordenone" },
  { value: "PO", label: "PO - Prato" },
  { value: "PR", label: "PR - Parma" },
  { value: "PT", label: "PT - Pistoia" },
  { value: "PU", label: "PU - Pesaro e Urbino" },
  { value: "PV", label: "PV - Pavia" },
  { value: "PZ", label: "PZ - Potenza" },
  { value: "RA", label: "RA - Ravenna" },
  { value: "RC", label: "RC - Reggio Calabria" },
  { value: "RE", label: "RE - Reggio Emilia" },
  { value: "RG", label: "RG - Ragusa" },
  { value: "RI", label: "RI - Rieti" },
  { value: "RM", label: "RM - Roma" },
  { value: "RN", label: "RN - Rimini" },
  { value: "RO", label: "RO - Rovigo" },
  { value: "SA", label: "SA - Salerno" },
  { value: "SI", label: "SI - Siena" },
  { value: "SO", label: "SO - Sondrio" },
  { value: "SP", label: "SP - La Spezia" },
  { value: "SR", label: "SR - Siracusa" },
  { value: "SS", label: "SS - Sassari" },
  { value: "SU", label: "SU - Sud Sardegna" },
  { value: "SV", label: "SV - Savona" },
  { value: "TA", label: "TA - Taranto" },
  { value: "TE", label: "TE - Teramo" },
  { value: "TN", label: "TN - Trento" },
  { value: "TO", label: "TO - Torino" },
  { value: "TP", label: "TP - Trapani" },
  { value: "TR", label: "TR - Terni" },
  { value: "TS", label: "TS - Trieste" },
  { value: "TV", label: "TV - Treviso" },
  { value: "UD", label: "UD - Udine" },
  { value: "VA", label: "VA - Varese" },
  { value: "VB", label: "VB - Verbano-Cusio-Ossola" },
  { value: "VC", label: "VC - Vercelli" },
  { value: "VE", label: "VE - Venezia" },
  { value: "VI", label: "VI - Vicenza" },
  { value: "VR", label: "VR - Verona" },
  { value: "VT", label: "VT - Viterbo" },
  { value: "VV", label: "VV - Vibo Valentia" },
  { value: "EE", label: "EE - Stato estero" },
];
